# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sumo Logic Developers
email: mfloyd5218@gmail.com
description: # Open Source Projects supporting the Sumo Logic service
baseurl: "https://codejournalist.github.io/" # the subpath of your site, e.g. /blog
url: "https://codejournalist.github.io" 

repository: https://github.com/CodeJournalist/codejournalist.github.io
timezone: America/Los_Angeles

# Build settings
markdown: kramdown

# Collections
collections:
   opensource_projects:
   output: true

exclude:
  - README.md
  - .gitignore